---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: guestbook
  labels:
    k8s-app: guestbook
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: guestbook
  endpoints:
  - port: http-server
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
